common:
  pkg.installed:
    - pkgs:
        - ack
        - aspell-en
        - aspell-fr
        - feh
        - git
        - lxterminal
        - htop
        - net-tools
        - reflector
        - sudo
        - ttf-bitstream-vera
        - ttf-ubuntu-font-family
        - gvim
        - xmobar
        - xclip
        - xorg-xinit
        - xorg-xsetroot
        - xorg-server
        - zsh
